### ISSUE TITLE
Use kube secrets for sensitive credentials

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#181]
aws cli, github, dockerhub, etc
```
kubectl create secret \
  generic mysecrets \
    ...
   --from-file=...
```

**Comment by cfregly** [comment]
```
kubectl create secret \
  generic <credentials-name> --type=string \
  --from-literal=user=<credentials-username> \
  --from-literal=password=<credentials-password>
```

**Comment by cfregly** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/distribute-credentials-secure/#creating-a-pod-that-has-access-to-the-secret-data-through-environment-variables

**Comment by cfregly** [comment]
* Configurate Pod to load secrets through files mounted from Volume
```
apiVersion: v1
kind: Pod
...
spec:
  containers:
    - name: ....
      image: ...
      volumeMounts:
          # name must match the volume name below
          - name: secret-volume
            mountPath: /etc/secret-volume
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: <credentials-name>
```

* Display secrets
```
cat /etc/secret-volume/username
cat /etc/secret-volume/password
```

**Comment by cfregly** [comment]
* Configure Pod to load secrets into ENV variables
```
apiVersion: v1
kind: Pod
...
spec:
  containers:
    - name: ....
      image: ...
    env:
    - name: CREDENTIALS_USERNAME
      valueFrom:
        secretKeyRef:
          name: <credentials-name>
          key: username
    - name: CREDENTIALS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: <credentials-name>
          key: password
 ```

* Display secrets
```
printenv
```

**Comment by cfregly** [comment]
https://kubernetes.io/docs/user-guide/secrets/

* Create ssh keys
```
kubectl create secret generic <ssh-keys-name> \
  --from-file=private-key=<path-to-id_rsa-file> \
  --from-file=publickey=<path-to-id_rsa.pub-file>
```

* Configure Pod to load secret ssh keys through files mounted from Volume
```
apiVersion: v1
kind: Pod
...
spec:
  containers:
    - name: ....
      image: ...
      volumeMounts:
          # name must match the volume name below
          - name: secret-volume
            mountPath: /etc/secret-volume
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: <ssh-keys-name>
```

* Display ssh key files inside container
```
ls -l /etc/secret-volume/

### EXPECTED OUTPUT ###
id-rsa.pub
id-rsa
```
